FROM ubuntu:16.04

MAINTAINER minhkma

RUN apt-get update 
RUN apt-get install -y dnsutils openssh-server vim net-tools inetutils-ping
RUN apt-get install -y inetutils-traceroute
RUN apt-get install -y inetutils-traceroute

CMD ["echo", "MinhKMA"]
